describe('inspect', function()

    describe('numbers', function()
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
        it('works', function()
            assert.equals("1", '1')
        end)
    end)
end)
